/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Conexion.ConexionBase;
import Entidades.Aulas;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Usuario
 */
public class GestionAulas extends javax.swing.JFrame {

    /**
     * Creates new form GestionAula
     */
    ConexionBase cb=new ConexionBase();
    private int  idAula;
    

    public int getIdAula() {
        return idAula;
    }

    public void setIdAula(int idAula) {
        this.idAula = idAula;
    }
    public GestionAulas() {
        initComponents();
        
        CargarTablaAulas ("");
    }
    public void CargarTablaAulas(String aula){
      DefaultTableModel Modelo =( DefaultTableModel )this.TablaAulas.getModel();
      Modelo.setRowCount(0);
        Connection base=ConexionBase.conexion;//conexion.getConnection();
        try{
            String sql = "call buscaraulas ('"+aula+"')";
            Statement consulta=base.createStatement();
            ResultSet resultado = consulta.executeQuery(sql);
            String[]fila=new String[4];
            while ( resultado.next()){
                fila[0]=resultado.getString(1);
                fila[1]=resultado.getString(2);
                fila[2]=resultado.getString(3);
                fila[3]=resultado.getString(4);
               
                Modelo.addRow(fila);
            }
            this.TablaAulas.setModel(Modelo);

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error de conexion"+e);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        TabAulas = new javax.swing.JTabbedPane();
        ListaAulas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAulas = new javax.swing.JTable();
        btnMod = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarAula = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        AgregarAula = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreAulaA = new javax.swing.JTextField();
        btnGuardarA = new javax.swing.JButton();
        btnCancelarA = new javax.swing.JButton();
        CapacidadA = new javax.swing.JSpinner();
        cbxEstadoA = new javax.swing.JComboBox<>();
        ModificarAula = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreAulaMod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGuardarM = new javax.swing.JButton();
        btnCancelarM = new javax.swing.JButton();
        CapacidadMod = new javax.swing.JSpinner();
        cbxEstadoMod = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idAula", "NombreAula", "Capacidad", "Estado"
            }
        ));
        jScrollPane1.setViewportView(TablaAulas);

        btnMod.setText("Modificar");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("     Buscar");

        txtBuscarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarAulaActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListaAulasLayout = new javax.swing.GroupLayout(ListaAulas);
        ListaAulas.setLayout(ListaAulasLayout);
        ListaAulasLayout.setHorizontalGroup(
            ListaAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaAulasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ListaAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListaAulasLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarAula, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ListaAulasLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ListaAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMod, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        ListaAulasLayout.setVerticalGroup(
            ListaAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaAulasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ListaAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ListaAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListaAulasLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnMod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar))
                    .addGroup(ListaAulasLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        TabAulas.addTab("Aulas", ListaAulas);

        jLabel2.setText("     Nombre del Aula ");

        jLabel3.setText("     Capacidad  ");

        jLabel4.setText("     Estado");

        btnGuardarA.setText("Guardar");
        btnGuardarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAActionPerformed(evt);
            }
        });

        btnCancelarA.setText("Cancelar");
        btnCancelarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAActionPerformed(evt);
            }
        });

        CapacidadA.setModel(new javax.swing.SpinnerNumberModel(20, 5, 100, 1));

        cbxEstadoA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitada", "Deshabilitada", "En reparación" }));

        javax.swing.GroupLayout AgregarAulaLayout = new javax.swing.GroupLayout(AgregarAula);
        AgregarAula.setLayout(AgregarAulaLayout);
        AgregarAulaLayout.setHorizontalGroup(
            AgregarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarAulaLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(AgregarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AgregarAulaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(AgregarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardarA)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(AgregarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxEstadoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarA)
                    .addComponent(txtNombreAulaA, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CapacidadA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        AgregarAulaLayout.setVerticalGroup(
            AgregarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarAulaLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(AgregarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreAulaA, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AgregarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CapacidadA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(AgregarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEstadoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(AgregarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarA)
                    .addComponent(btnCancelarA))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabAulas.addTab("AgregarAula", AgregarAula);

        jLabel5.setText(" Nombre del Aula ");

        jLabel6.setText("Capacidad  ");

        jLabel7.setText(" Estado");

        btnGuardarM.setText("Guardar");
        btnGuardarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMActionPerformed(evt);
            }
        });

        btnCancelarM.setText("Cancelar");
        btnCancelarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarMActionPerformed(evt);
            }
        });

        CapacidadMod.setModel(new javax.swing.SpinnerNumberModel(20, 5, 100, 1));

        cbxEstadoMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitada", "Deshabilitada", "En reparación" }));

        javax.swing.GroupLayout ModificarAulaLayout = new javax.swing.GroupLayout(ModificarAula);
        ModificarAula.setLayout(ModificarAulaLayout);
        ModificarAulaLayout.setHorizontalGroup(
            ModificarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarAulaLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(ModificarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ModificarAulaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(ModificarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardarM))))
                .addGap(26, 26, 26)
                .addGroup(ModificarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxEstadoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarM)
                    .addComponent(txtNombreAulaMod, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CapacidadMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        ModificarAulaLayout.setVerticalGroup(
            ModificarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarAulaLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(ModificarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreAulaMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModificarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CapacidadMod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEstadoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(ModificarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarM)
                    .addComponent(btnCancelarM))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        TabAulas.addTab("ModificarAula", ModificarAula);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabAulas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        // TODO add your handling code here:
        int fila=this.TablaAulas.getSelectedRow();
        this.idAula=Integer.valueOf(this.TablaAulas.getValueAt(fila, 0).toString());
        this.txtNombreAulaMod.setText(this.TablaAulas.getValueAt(fila, 1).toString());
        this.CapacidadMod.setValue(Integer.valueOf(this.TablaAulas.getValueAt(fila, 2).toString()));
        this.cbxEstadoMod.setSelectedItem(this.TablaAulas.getValueAt(fila, 3).toString());
        this.TabAulas.getComponentAt(2).show();
        TabAulas.setSelectedIndex(2);
    }//GEN-LAST:event_btnModActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        this.TabAulas.getComponentAt(1).show();
        TabAulas.setSelectedIndex(1);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila=this.TablaAulas.getSelectedRow();
        idAula=Integer.valueOf(this.TablaAulas.getValueAt(fila, 0).toString());
        Aulas A1=new Aulas(idAula);
        A1.EliminarAula();
        this.CargarTablaAulas("");
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAActionPerformed
        // TODO add your handling code here:
        this.TabAulas.getComponentAt(0).show();
        TabAulas.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarAActionPerformed

    private void btnCancelarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarMActionPerformed
        // TODO add your handling code here:
        this.TabAulas.getComponentAt(0).show();
        TabAulas.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarMActionPerformed

    private void btnGuardarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAActionPerformed
        String nombreaula=this.txtNombreAulaA.getText();
        int capacidad=Integer.valueOf(this.CapacidadA.getValue().toString());
        String estado=this.cbxEstadoA.getSelectedItem().toString();
        Aulas a=new Aulas(nombreaula, capacidad, estado);
        a.RegistrarAula();
        this.CargarTablaAulas("");
        this.TabAulas.getComponentAt(0).show();
        TabAulas.setSelectedIndex(0);       
    }//GEN-LAST:event_btnGuardarAActionPerformed

    private void btnGuardarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMActionPerformed
        // TODO add your handling code here:
        String nombreaula=this.txtNombreAulaMod.getText();
        int capacidad=Integer.valueOf(this.CapacidadMod.getValue().toString());
        String estado=this.cbxEstadoMod.getSelectedItem().toString();
        Aulas a=new Aulas(idAula,nombreaula, capacidad, estado);
        a.ModificarAula();
        this.CargarTablaAulas("");
        this.TabAulas.getComponentAt(0).show();
        TabAulas.setSelectedIndex(0);    
        
    }//GEN-LAST:event_btnGuardarMActionPerformed

    private void txtBuscarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarAulaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CargarTablaAulas(this.txtBuscarAula.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAulas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAulas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarAula;
    private javax.swing.JSpinner CapacidadA;
    private javax.swing.JSpinner CapacidadMod;
    private javax.swing.JPanel ListaAulas;
    private javax.swing.JPanel ModificarAula;
    private javax.swing.JTabbedPane TabAulas;
    private javax.swing.JTable TablaAulas;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelarA;
    private javax.swing.JButton btnCancelarM;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarA;
    private javax.swing.JButton btnGuardarM;
    private javax.swing.JButton btnMod;
    private javax.swing.JComboBox<String> cbxEstadoA;
    private javax.swing.JComboBox<String> cbxEstadoMod;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtBuscarAula;
    private javax.swing.JTextField txtNombreAulaA;
    private javax.swing.JTextField txtNombreAulaMod;
    // End of variables declaration//GEN-END:variables
}
